server:
  port: 8041

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: http://211.159.166.210:8848 #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080
        #dashboard: http://211.159.166.210:8080
        #clientIp: 211.159.166.210
        port: 8719 #默认8197，如果被占用会涌动从8719开始一次加1扫描，直到找到未被占用的端口
      web-context-unify: false #controller层对service层的调用不认为是同一个根链路
      datasource:
        ds1:
          nacos:
            server-addr: http://211.159.166.210:8848 #配置nacos地址
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow #com.alibaba.cloud.sentinel.datasource.Ruletype



