server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://211.159.166.210:8848 #配置nacos地址
#消费者将要去访问的微服务名称（nacos微服务提供者叫什么你写什么）
service-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
